[package]
name = "rust-ddd-login-example"
version = "0.1.0"
authors = ["Jordi Domènech Bonilla <jdomenechbborges@gmail.com>"]
edition = "2021"

[dependencies]
readonly = "0"
mockall = "0"
fake = {version="2", features=['derive']}
rand = "0"
